---
- name: Install dependencies and run Docker container
  hosts: all
  become: true
  tasks:
    - name: Ensure python3 and pip3 are installed
      package:
        name:
          - python3
          - python3-pip
        state: present
    - name: Install docker-py with pip3
      pip:
        name: docker-py
        executable: pip3
    - name: Install Docker and Docker Compose (using apt for Ubuntu/Debian)
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Run Docker container
      docker_container:
        name: wartest
        image: "{{ image }}"
        ports:
          - "8082:8080"
        state: started
